# -*- coding: utf-8 -*-
"""member1_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOVwfQe9CiefGQzuATP8gpFANZZ85poh
"""

import pandas as pd

df = pd.read_csv("fakenews.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
print(df.head())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicated rows:", df.duplicated().sum())

df = df.drop_duplicates()
print(f"After removing duplicates, the new shape is: {df.shape}")

import string

# 去除标点、转换小写
df['text'] = df['text'].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)).lower())

# 检查清洗后的结果
print(df.head())

from sklearn.model_selection import train_test_split

# 7:1:2 划分
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    df['text'], df['label'], test_size=0.3, random_state=42, stratify=df['label']
)
val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels, test_size=0.6667, random_state=42, stratify=temp_labels
)

print(f"Train size: {len(train_texts)}")
print(f"Validation size: {len(val_texts)}")
print(f"Test size: {len(test_texts)}")

from sklearn.feature_extraction.text import TfidfVectorizer

# 建立 TF-IDF 向量器
tfidf_vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

# 只在训练集上 fit
X_train_tfidf = tfidf_vectorizer.fit_transform(train_texts)

# 验证集和测试集只做 transform
X_val_tfidf = tfidf_vectorizer.transform(val_texts)
X_test_tfidf = tfidf_vectorizer.transform(test_texts)

print("X_train_tfidf shape:", X_train_tfidf.shape)
print("X_val_tfidf shape:", X_val_tfidf.shape)
print("X_test_tfidf shape:", X_test_tfidf.shape)

print("Train label distribution:")
print(train_labels.value_counts())

print("\nValidation label distribution:")
print(val_labels.value_counts())

print("\nTest label distribution:")
print(test_labels.value_counts())

import numpy as np

y_train = np.array(train_labels)
y_val = np.array(val_labels)
y_test = np.array(test_labels)

print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

import scipy.sparse as sp

# 保存 TF-IDF 稀疏矩阵
sp.save_npz("X_train_tfidf.npz", X_train_tfidf)
sp.save_npz("X_val_tfidf.npz", X_val_tfidf)
sp.save_npz("X_test_tfidf.npz", X_test_tfidf)

# 保存标签
np.save("y_train.npy", y_train)
np.save("y_val.npy", y_val)
np.save("y_test.npy", y_test)

print("Saved TF-IDF features and labels successfully.")

import joblib

joblib.dump(tfidf_vectorizer, "tfidf_vectorizer.pkl")
print("Saved tfidf_vectorizer.pkl successfully.")

import scipy.sparse as sp
import numpy as np
import joblib

X_train_loaded = sp.load_npz("X_train_tfidf.npz")
X_val_loaded = sp.load_npz("X_val_tfidf.npz")
X_test_loaded = sp.load_npz("X_test_tfidf.npz")

y_train_loaded = np.load("y_train.npy")
y_val_loaded = np.load("y_val.npy")
y_test_loaded = np.load("y_test.npy")

vectorizer_loaded = joblib.load("tfidf_vectorizer.pkl")

print("X_train_loaded shape:", X_train_loaded.shape)
print("X_val_loaded shape:", X_val_loaded.shape)
print("X_test_loaded shape:", X_test_loaded.shape)

print("y_train_loaded shape:", y_train_loaded.shape)
print("y_val_loaded shape:", y_val_loaded.shape)
print("y_test_loaded shape:", y_test_loaded.shape)

df["text_length"] = df["text"].apply(lambda x: len(str(x).split()))

print("Average text length:", df["text_length"].mean())
print("Max text length:", df["text_length"].max())
print("Min text length:", df["text_length"].min())

print("\nText length description:")
print(df["text_length"].describe())

train_lengths = train_texts.apply(lambda x: len(str(x).split()))
val_lengths = val_texts.apply(lambda x: len(str(x).split()))
test_lengths = test_texts.apply(lambda x: len(str(x).split()))

print("Train average text length:", train_lengths.mean())
print("Validation average text length:", val_lengths.mean())
print("Test average text length:", test_lengths.mean())

import torch
from torch.utils.data import Dataset, DataLoader

class FakeNewsDataset(Dataset):
    def __init__(self, features, labels):
        self.features = torch.tensor(features.toarray(), dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

train_dataset = FakeNewsDataset(X_train_tfidf, y_train)
val_dataset = FakeNewsDataset(X_val_tfidf, y_val)
test_dataset = FakeNewsDataset(X_test_tfidf, y_test)

print("Train dataset size:", len(train_dataset))
print("Validation dataset size:", len(val_dataset))
print("Test dataset size:", len(test_dataset))

BATCH_SIZE = 32

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

print("Train loader batches:", len(train_loader))
print("Validation loader batches:", len(val_loader))
print("Test loader batches:", len(test_loader))

sample_features, sample_labels = next(iter(train_loader))

print("Sample feature batch shape:", sample_features.shape)
print("Sample label batch shape:", sample_labels.shape)
print("Feature dtype:", sample_features.dtype)
print("Label dtype:", sample_labels.dtype)

import pandas as pd

train_df = pd.DataFrame({"text": train_texts, "label": train_labels})
val_df = pd.DataFrame({"text": val_texts, "label": val_labels})
test_df = pd.DataFrame({"text": test_texts, "label": test_labels})

train_df.to_csv("train_split.csv", index=False)
val_df.to_csv("val_split.csv", index=False)
test_df.to_csv("test_split.csv", index=False)

print("Saved train_split.csv, val_split.csv, test_split.csv")

df["text_length"] = df["text"].apply(lambda x: len(str(x).split()))

print("Average text length:", df["text_length"].mean())
print("Max text length:", df["text_length"].max())
print("Min text length:", df["text_length"].min())

print("\nText length description:")
print(df["text_length"].describe())

dataset_statistics_text = """Dataset Statistics Report

Dataset name: fakenews.csv

1. Original Dataset Information
- Original number of samples: 4986
- Number of columns: 2
- Column names: text, label

2. Data Quality Check
- Missing values in text column: 0
- Missing values in label column: 0
- Number of duplicated rows: 237

3. Cleaned Dataset Information
- Number of samples after removing duplicates: 4749

4. Label Distribution
- Training set:
  - Label 0: 2017
  - Label 1: 1307
- Validation set:
  - Label 0: 287
  - Label 1: 187
- Test set:
  - Label 0: 577
  - Label 1: 374

5. Dataset Split
- Training set size: 3324
- Validation set size: 474
- Test set size: 951
- Split ratio: 7:1:2
- Random seed: 42
- Stratified sampling: Yes

6. Text Length Statistics
- Text length was calculated based on the number of words in each news sample.
- Average text length: 651.7663
- Maximum text length: 17116
- Minimum text length: 4
- Standard deviation: 1288.7091
- 25th percentile: 213
- Median (50th percentile): 360
- 75th percentile: 577

7. TF-IDF Feature Matrix
- X_train_tfidf shape: (3324, 5000)
- X_val_tfidf shape: (474, 5000)
- X_test_tfidf shape: (951, 5000)

8. Label Array Shapes
- y_train shape: (3324,)
- y_val shape: (474,)
- y_test shape: (951,)
"""

with open("dataset_statistics.txt", "w", encoding="utf-8") as f:
    f.write(dataset_statistics_text)

preprocessing_notes_text = """Data Preprocessing Notes

This document describes the preprocessing steps for the Fake News Detection project.

1. Dataset Loading
The dataset used in this project is fakenews.csv. It contains two columns:
- text: the news content
- label: the class label

2. Data Inspection
The dataset was first checked for:
- total number of samples
- column names
- missing values
- duplicated rows

The inspection showed that there were no missing values, but duplicated rows existed.

3. Data Cleaning
The following preprocessing steps were applied:
- removed duplicated rows
- converted all text to lowercase
- removed punctuation and special symbols

No missing-value removal was needed because the dataset contained no null values.

4. Dataset Splitting
The cleaned dataset was split into:
- training set
- validation set
- test set

The split ratio was 7:1:2, with random seed 42.
Stratified sampling was used to keep label distribution consistent across all subsets.

5. Text Feature Engineering
TF-IDF was selected as the main text representation method.

The following TF-IDF settings were used:
- max_features = 5000
- stop_words = 'english'

The TF-IDF vectorizer was fitted only on the training set:
- fit_transform() on training data
- transform() on validation and test data

This prevents data leakage.

6. Output Files
The following output files were generated:
- X_train_tfidf.npz
- X_val_tfidf.npz
- X_test_tfidf.npz
- y_train.npy
- y_val.npy
- y_test.npy
- tfidf_vectorizer.pkl
- train_split.csv
- val_split.csv
- test_split.csv

7. DataLoader Preparation
A custom PyTorch Dataset class was created to convert TF-IDF features and labels into tensors.
DataLoader objects were built for:
- training set
- validation set
- test set

The batch size was set to 32.

DataLoader statistics:
- Train loader batches: 104
- Validation loader batches: 15
- Test loader batches: 30

8. Notes for Group Member 2
Member 2 can directly use:
- the saved TF-IDF feature matrices
- the saved label arrays
- the TF-IDF vectorizer
- the train/validation/test split files

These files are ready for model training and validation.
"""

with open("preprocessing_notes.txt", "w", encoding="utf-8") as f:
    f.write(preprocessing_notes_text)

print("Saved dataset_statistics.txt and preprocessing_notes.txt")

import zipfile

files_to_zip = [
    "X_train_tfidf.npz",
    "X_val_tfidf.npz",
    "X_test_tfidf.npz",
    "y_train.npy",
    "y_val.npy",
    "y_test.npy",
    "tfidf_vectorizer.pkl",
    "train_split.csv",
    "val_split.csv",
    "test_split.csv",
    "dataset_statistics.txt",
    "preprocessing_notes.txt"
]

with zipfile.ZipFile("member1_outputs.zip", "w") as zipf:
    for file in files_to_zip:
        zipf.write(file)

print("Created member1_outputs.zip successfully.")

from google.colab import files
files.download("member1_outputs.zip")

import os
print(os.listdir())